version: '3.5'

services:
  database:
    image: postgres:12
    restart: always
    volumes: 
      - server_db:/var/lib/postgresql/data/
    env_file: 
      - .production.env
    ports:
      - 5432:5432      

  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules    
    env_file:
      - .production.env
    depends_on: 
      - database
    ports:
      - 3000:3000

volumes: 
  server_db:
