version: '3.5'

services:
  database:
    image: postgres:12
    restart: always
    volumes: 
      - server_db:/var/lib/postgresql/data/
    env_file: 
      - .production.env
    ports:
      - 5432:5432      

  api:
    build: .
    env_file:
      - .production.env
    depends_on: 
      - database
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"

  traefik:
    image: traefik:latest
    restart: always
    volumes: 
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - .production.env
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.ipwhitelist.ipwhitelist.sourcerange=127.0.0.1/32, 104.60.90.194"
      - "traefik.http.routers.traefik.service=api@internal"

volumes: 
  server_db:

networks: 
  default: 
    external:
      name: "traefik-network"
