api:
  debug: true
  dashboard: true

entryPoints:
  insecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: secure
          scheme: https
  secure:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: landale.app
            sans:
                - "*.landale.app"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.landale.app`)"
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: bryan@avalonstar.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  http:
    acme:
      email: bryan@avalonstar.com
      storage: acme.json
      httpChallenge:
        entryPoint: insecure

log:
  level: DEBUG
  filepath: "/etc/traefik/log/traefik.log"

accessLog:
  filePath: /log/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - 200
      - 300-302
      - 400-499
      - 500-599
    retryAttempts: true
    minDuration: 10ms