log:
  level: DEBUG
  filepath: "/etc/traefik/log/traefik.log"
api:
  debug: true
  insecure: true
  dashboard: true
entryPoints:
  insecure:
    address: ":80"
  secure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "traefik-network"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_config.yml"
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: bryan@avalonstar.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
  